./gameboy BROKER NEW_POKEMON A 1 2 3
./gameboy BROKER APPEARED_POKEMON AB 1 2 3
./gameboy BROKER CATCH_POKEMON ABC 1 2
./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER GET_POKEMON ABCD
./gameboy BROKER LOCALIZED_POKEMON 1 ABCDE 2 1 1 2 2